### ISSUE TITLE
榜单自动评估

### ISSUE THREAD

**Issue by lengyueyang** [FreedomIntelligence/CMB#1]
多谢这么优秀的工作，请问下榜单可以做成自动评估吗？

发邮件评估的方式比较费事费力，希望榜单能做成自动评估，更方便一些

**Comment by wangxidong06** [comment]
感谢您的认可和建议，榜单的自动评估和论文撰写在同时进行，预计论文公开时可以上线自动评估系统。再次感谢您的建议和关注。
