### ISSUE TITLE
add Baichuan2-53b and ChatGLM3 evaluation results

### ISSUE THREAD

**Issue by WangRongsheng** [FreedomIntelligence/CMB#12]
You can check evaluation results (Zero-Shot) about Baichuan2-53b and ChatGLM3.

- https://github.com/WangRongsheng/CareGPT/tree/main/eval
- https://github.com/WangRongsheng/CareGPT/tree/main#%E6%A8%A1%E5%9E%8B%E8%AF%84%E6%B5%8B

Thank you!

**Comment by wangxidong06** [comment]
Thanks for your contribution !
