### ISSUE TITLE
您好，请问SAT框架下微调得到的模型该如何使用CMB呢

### ISSUE THREAD

**Issue by Boom-Bamboo** [FreedomIntelligence/CMB#15]
您好，我使用了SAT框架微调了chatglm，此时该如何使用CMB呢，能否提供一个示例脚本呢？十分感谢！

**Comment by Boom-Bamboo** [comment]
> 您好，推理应该于训练无关，您是有什么报错嘛？
抱歉，是我问题描述的不清楚。我刚刚接触LLM，尝试使用SAT框架微调了chatglm-6b，但得到的模型并不能直接被CMB读取。您先前给出了transformers和peft下的运行示例，所以我尝试让CMB读取sat框架下的模型文件。

目前我根据SAT官方示例[](https://github.com/THUDM/SwissArmyTransformer/blob/main/examples/chatglm/chat.py)以及chatglm3的运行脚本[](https://github.com/WangRongsheng/CareGPT/blob/main/eval/eval_chatglm36b.py)。
得到了读取SAT模型并且进行评测的脚本👇
[](https://github.com/Boom-Bamboo/Boom-Bamboo/tree/main)

您可以测试一下这两个脚本能否正确运行吗？十分感谢您了！因为我还是个菜鸟很多代码并没有读懂，不能确定是否得到了正确的结果😔

**Comment by wangxidong06** [comment]
您好，如果有报错请您直接呈现报错信息，如果没有，我这边默认为正确运行。
