### ISSUE TITLE
您好，請問此項目中的val集是否能產生分數?

### ISSUE THREAD

**Issue by FrancyFan** [FreedomIntelligence/CMB#18]
如题

**Comment by wangxidong06** [comment]
您好，可以依据val集合产生分数并作为参考。同时，我们也在官网提供了返回test集分数的接口，使用起来也同样方便。

**Comment by FrancyFan** [comment]
> 您好，可以依据val集合产生分数并作为参考。同时，我们也在官网提供了返回test集分数的接口，使用起来也同样方便。

您好，我不太了解要如何跑出分数，所以我目前的做法是将val集合的答案与描述剃除后再将每个val集合的问题标注id然后跑评测，然后再自己写程序计算准确率(但多选不知道怎么算，目前是要全答对才算对)，请问你能提供更多资讯嘛?

**Comment by wangxidong06** [comment]
多选官网的测评是需要全答对才算对。
