### ISSUE TITLE
What is the provenance of CMB datasets?

### ISSUE THREAD

**Issue by zhimin-z** [FreedomIntelligence/CMB#20]

**Comment by zhimin-z** [comment]
Check https://medbench.opencompass.org.cn/docs

**Comment by wangxidong06** [comment]
Course examinations for medical students at school, textbook questions, graduate entrance examinations, professional qualification examinations, and professional title assessment examinations.

**Comment by wangxidong06** [comment]
Regarding the differences, CMB was released on August 1, 2023, covering examinations for various career growth paths of physicians, pharmacists, medical technicians, and nurses.
