### ISSUE TITLE
Please fix the error in the test set.

### ISSUE THREAD

**Issue by WangRongsheng** [FreedomIntelligence/CMB#21]
The erros is:

`CMB-test-choice-question-merge.json`
```json
{
        "id": 5205,
        "exam_type": "药师考试",
        "exam_class": "初级中药士",
        "exam_subject": "中药学（士）",
        "question": "以下哪个药材饮片应建立专账，由专人管理",
        "question_type": "多项选择题",
        "option": {
            "A": "牛黄",
            "B": "罂粟壳",
            "C": "羚羊角",
            "D": "龙眼肉",
            "E": "石斛",
            "F": "2"
        }
```
`CMB-test-choice-answer.json`
```json
{
        "id": 5205,
        "exam_type": "药师考试",
        "exam_class": "初级中药士",
        "exam_subject": "中药学（士）",
        "question_type": "多项选择题",
        "answer": "毒性中药和麻醉中药决不能放一般药斗内必须专柜、专账由专人管理严防意外恶性事故的发生。"
    },
```

**Comment by WangRongsheng** [comment]
Please fix the error with id 5205, 5211, 5219, 5230, 5235, 5236, 5238, 5241, 5287, 5319, 5375, 5376, 5419, 5421, 5424, 5430, 5435, 5452, 5466, 5481, 5482, 5491, 5516, 5522, 5530, 5548, 5555, 5594, and 5596 in the test set.

**Comment by wangxidong06** [comment]
Thank you for your reminder. It has been found that there is a problem with the newly public test set answers. We will update and correct it as soon as possible. Thank you!

**Comment by wangxidong06** [comment]
Hello, sorry to keep you waiting. After checking, it is found that the version of our public test set is wrong. We have re-uploaded it. Thank you for your use and reminder.
