### ISSUE TITLE
CMB测评网站提示上传失败

### ISSUE THREAD

**Issue by libbrrary** [FreedomIntelligence/CMB#24]
您好！我在上传测评文件时遇到了错误，经过验证，也不是文件的问题
![1](https://github.com/FreedomIntelligence/CMB/assets/113362833/23b59d74-8384-4c66-81c5-64c8f90992aa)

**Comment by ridgerchu** [comment]
也遇到了一样的问题。。

**Comment by wangxidong06** [comment]
不好意思，后台服务已经挂起了，请大家再试一下。十分抱歉。
