### ISSUE TITLE
KeyError: 'qwen2'，请问是不支持qwen1.5系列吗？

### ISSUE THREAD

**Issue by Egber1t** [FreedomIntelligence/CMB#25]
望解答谢谢！
1.在model_config.yaml文件加入了：
Qwen1.5-0.5B-Chat: # the public version on HF 
    model_id: "Qwen1.5-0.5B-Chat"
    load:
        config_dir: "/root/autodl-tmp/model/Qwen1.5-0.5B-Chat"
        device: 'cuda'        
        precision: 'fp16'
    generation_config: 
        max_new_tokens: 512     
        min_new_tokens: 1          
        do_sample: False       

2.mymodel没有做修改

3.   在constants文件加入了：
 'Qwen1.5-0.5B-Chat': MyModelWorker, # modify here

4.最后一步运行为：
input_path='/root/autodl-tmp/CMB_datasetes/data/CMB-test-choice-answer.json'   # CMB-Exam
# input_path='./data/CMB-Clin/CMB-Clin-qa.json'                             # CMB-Clin

task_name='Exam' 

model_id="Qwen1.5-0.5B-Chat" # which model to evaluate
mkdir -p logs/${task_name}/

accelerate launch --main_process_port 27274 --config_file /root/autodl-tmp/CMB/configs/accelerate_config.yaml  /root/autodl-tmp/CMB/src/generate_answers.py \
--use_cot \
--model_id=$model_id \
--all_gather_freq=20 \
--input_path=$input_path \
--output_path=./result/${task_name}/${model_id}/modelans.json \
--batch_size 1 \
--model_config_path="/root/autodl-tmp/CMB/configs/model_config.yaml" 

5.运行后报错：KeyError: 'qwen2'

环境如下：
torch                          2.1.2+cu121
torchvision                    0.16.2+cu121
transformers                   4.33.1
transformers-stream-generator  0.0.5
accelerate                     0.30.0
peft                           0.10.0
omegaconf                      2.3.0
sentence-transformers          2.2.2
sentencepiece                  0.2.0

**Comment by wangxidong06** [comment]
You can solve it by upgrading 'transformers'

pip uninstall transformers
pip install --upgrade transformers==4.37.0

**Comment by Egber1t** [comment]
@wangxidong06 感谢您的及时回复，在升级后。
运行命令：
(cmb) root@autodl-container-9fac4facfe-28051fb2:~/autodl-tmp/CMB# bash generate_answers.sh
output to ./result/Exam/Qwen1.5-0.5B-Chat
...
loading config: {'config_dir': '/root/autodl-tmp/model/Qwen1.5-0.5B-Chat', 'device': 'cuda', 'precision': 'fp16'}
...
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
看样子已经加载进来了，但是提示GPU出问题了

报错：
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

检查显卡（48G）使用情况后，并未其他任务占用显存。而后使用命令：export CUDA_VISIBLE_DEVICES=0

还是报上述相同错误，求解答，谢谢！

**Comment by wangxidong06** [comment]
export NCCL_DEBUG=INFO
export NCCL_DEBUG=TRACE
查看子进程报错

**Comment by Egber1t** [comment]
@wangxidong06 您好，我换成Baichuan2-7B-Chat也是同样报错，如下：

autodl-container-bb57458a71-0ed3fd67:4318:4318 [0] NCCL INFO Bootstrap : Using eth0:172.17.0.12<0>
autodl-container-bb57458a71-0ed3fd67:4318:4318 [0] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
autodl-container-bb57458a71-0ed3fd67:4318:4318 [0] NCCL INFO cudaDriverVersion 12040
NCCL version 2.20.5+cuda12.4
autodl-container-bb57458a71-0ed3fd67:4318:4370 [0] NCCL INFO NET/IB : No device found.
autodl-container-bb57458a71-0ed3fd67:4318:4370 [0] NCCL INFO NET/Socket : Using [0]eth0:172.17.0.12<0>
autodl-container-bb57458a71-0ed3fd67:4318:4370 [0] NCCL INFO Using non-device net plugin version 0
autodl-container-bb57458a71-0ed3fd67:4318:4370 [0] NCCL INFO Using network Socket
W0508 11:28:30.255000 139965139388224 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 4318 closing signal SIGTERM
E0508 11:28:30.369000 139965139388224 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 1 (pid: 4319) of binary: /root/miniconda3/bin/python。

torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/root/autodl-tmp/CMB/src/generate_answers.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-08_11:28:30
  host      : autodl-container-bb57458a71-0ed3fd67
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 4319)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by Egber1t** [comment]
我看这里是多gpu模式，我把gpu_ids和 num_processes改成1，也是不行，求解答
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: '0,1,2,3'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 8  # number of GPUs
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by wangxidong06** [comment]
确保 LD_LIBRARY_PATH 环境变量包括指向 NCCL 库的路径。

`export LD_LIBRARY_PATH=/path/to/nccl/lib:$LD_LIBRARY_PATH`

替换 /path/to/nccl/lib 为实际的 NCCL 库安装路径。 确认权限和路径

**Comment by Egber1t** [comment]
已解决谢谢

**Comment by Egber1t** [comment]
@wangxidong06 您好，在运Qwen-7B-chat出现报错‘ImportError: This modeling file requires the following packages that were not found in your environment: transformers_stream_generator. Run `pip install transformers_stream_generator`’，
我在路径下已安装transformers_stream_generator==0.05，求解答谢谢！

**Comment by wangxidong06** [comment]
你可以试着自己import一下 看是否成功 没有找到就重新卸载安装
