### ISSUE TITLE
请问评分问题

### ISSUE THREAD

**Issue by Egber1t** [FreedomIntelligence/CMB#26]
您好，我用qwen-7B-chat模型进行评测后为什么得分这么低？
        "医师考试": 0.059,
        "护理考试": 0.115625,
        "药师考试": 0.0671875,
        "医技考试": 0.12916666666666668,
        "专业知识考试": 0.00375,
        "医学考研": 0.065
与官方的40多分相差甚远，求解答

**Comment by wangxidong06** [comment]
请看一下模型生成的答案，或者上传一下模型答案的样例

**Comment by Egber1t** [comment]
您好！
这个是提示词的部分，没有任何改动
    @property
    def system_prompt(self):
        return "一位用户和智能医疗大模型HuatuoGPT之间的对话。对于用户的医疗问诊，HuatuoGPT给出准确的、详细的、温暖的指导建议。对于用户的指令问题，HuatuoGPT给出有益的、详细的、有礼貌的回答。"
    @property
    def instruction_template(self):
        return self.system_prompt + '问：{instruction}\n答：'
    @property
    def instruction_template_with_fewshot(self,):
        return self.system_prompt + '{fewshot_examples}问：{instruction}\n答：'
    @property
    def fewshot_template(self):
        return "问：{user}\n答：{gpt}\n"
    
    def collate_conv(self, data):
        raise NotImplementedError



这是预测出来的部分文件，我看了一下model answer的选项至少很多都是对的，求解答谢谢！
[
    {
        "id": 1,
        "exam_type": "医师考试",
        "exam_class": "规培结业",
        "exam_subject": "临床病理科",
        "question": "下列有关鳃弓的描述，错误的是",
        "question_type": "单项选择题",
        "option": {
            "A": "由间充质增生形成",
            "B": "人胚第4周出现",
            "C": "相邻鳃弓之间为鳃沟",
            "D": "共5对鳃弓",
            "E": "位于头部两侧"
        },
        "option_str": "A. 由间充质增生形成\nB. 人胚第4周出现\nC. 相邻鳃弓之间为鳃沟\nD. 共5对鳃弓\nE. 位于头部两侧",
        "query": "一位用户和智能医疗大模型HuatuoGPT之间的对话。对于用户的医疗问诊，HuatuoGPT给出准确的、详细的、温暖的指导建议。对于用户的指令问题，HuatuoGPT给出有益的、详细的、有礼貌的回答。问：以下是中国医师考试中规培结业考试的一道单项选择题，请分析每个选项，并最后给出答案。\n下列有关鳃弓的描述，错误的是\nA. 由间充质增生形成\nB. 人胚第4周出现\nC. 相邻鳃弓之间为鳃沟\nD. 共5对鳃弓\nE. 位于头部两侧\n答：",
        "answer_0": "鳃弓是由间充质增生形成的，人胚在第4周出现，相邻鳃弓之间为鳃裂，共有4对鳃弓，位于头部两侧。所以，正确答案是A。",
        "model_answer": "A"

**Comment by wangxidong06** [comment]
对的

**Comment by Egber1t** [comment]
@wangxidong06 
您好，改完system prompt和roleA(问:) roleB(答:) ，依旧分数依旧低于1.
![image](https://github.com/FreedomIntelligence/CMB/assets/137043350/6cecefec-57a6-4764-94e0-9bc6f2719fd8)
模型生成答案为：
![image](https://github.com/FreedomIntelligence/CMB/assets/137043350/07baa842-402e-4314-a043-9371eecada27)
求解答，万分感谢！

**Comment by wangxidong06** [comment]
你这样改是错的，麻烦认真看一下回复。

```
def system_prompt(self):
     return "You are a helpful assistant."

def instruction_template(self):
     return self.system_prompt

def instruction_template_with_fewshot(self):
     return self.system_prompt + ’{fewshot_example}<|im_start|>user\n{instruction}<|im_start|>assistant\n‘

def fewshot_template(self):
     return "<|im_start|>user\n{user}<|im_start|>assistant\n{gpt}"
```

**Comment by Egber1t** [comment]
抱歉，我理解能力有限，还是没有看懂您回复的。您上面贴的这张我改了一下还是不行。
 ![image](https://github.com/FreedomIntelligence/CMB/assets/137043350/3e13109f-e06e-4234-a4ef-2dbc38b04c24)！
@wangxidong06 ，求指导谢谢！

**Comment by Egber1t** [comment]
还有就是后面两个property是在使用few shot调用吗？如果不用few shot是不是可以不用更改

**Comment by wangxidong06** [comment]
"还是不行" 是指什么

**Comment by Egber1t** [comment]
是指按下面这个代码更改完，得分变成0了。
![image](https://github.com/FreedomIntelligence/CMB/assets/137043350/dd6c0f1b-4ed0-4695-ba3c-7f4a6c7fa123)

**Comment by Egber1t** [comment]
def instruction_template(self):
     return self.system_prompt，是不是这两行出问题了

**Comment by wangxidong06** [comment]
`
def instruction_template(self,):
        return self.system_prompt + '<|im_start|>user\n{instruction}\n<|im_start|>assistant\n'
`

**Comment by Egber1t** [comment]
@wangxidong06 您好，按照您给的代码修改后（如下）
![image](https://github.com/FreedomIntelligence/CMB/assets/137043350/a711bcbb-82af-4cd8-8233-2a52d568dcab)
生成的答案如下图：
![image](https://github.com/FreedomIntelligence/CMB/assets/137043350/9406746b-f79d-40d3-a6b4-ce92d6017975)
把这个json提交至官网给出的得分如下图：
![image](https://github.com/FreedomIntelligence/CMB/assets/137043350/5d8f9b70-dfdf-4b7d-bab8-7cdf476f9c4d)

**Comment by Egber1t** [comment]
我也把生成的json文件仿照官网samples进行处理得到如下：
![image](https://github.com/FreedomIntelligence/CMB/assets/137043350/b86c2d94-b062-4e25-becc-35a6c5df4609)
得分依旧跟没处理一样，求解答，谢谢！

**Comment by wangxidong06** [comment]
你已经测评正确了，谢谢！

**Comment by Egber1t** [comment]
那请问为什么官网qwen-7b-chat都很高
![image](https://github.com/FreedomIntelligence/CMB/assets/137043350/fe273761-fb10-4496-b449-038ead834b9b)
我这个连1都没到？还是说，我评测出来后应该算百分比？

**Comment by wangxidong06** [comment]
测评得分是准确率(0-1), 你直接换算成百分比就好了

**Comment by Egber1t** [comment]
谢谢，万分感谢！
