### ISSUE TITLE
CMB测评网站提示上传失败 :Error uploading file,Please try again

### ISSUE THREAD

**Issue by wandouguo** [FreedomIntelligence/CMB#27]
![image](https://github.com/FreedomIntelligence/CMB/assets/9603390/153e5039-4be5-4555-b7f7-f58829d58d1b)

**Comment by wangxidong06** [comment]
服务已恢复。

**Comment by 990934110** [comment]
又出现这个问题了

**Comment by wangxidong06** [comment]
不好意思，我们的服务器宕机，正在联系新服务器，我们正在加紧修复，CMB仍会运行。您可以通过运行https://github.com/FreedomIntelligence/CMB/tree/main?tab=readme-ov-file#run-evaluation-and-submit 中的代码，获得您的分数。
