### ISSUE TITLE
CME官方提交入口报错

### ISSUE THREAD

**Issue by yuyaxiong** [FreedomIntelligence/CMB#3]
使用提交页面中的sample.json进行任务提交，发现如下报错，劳烦帮忙看下页面是否有异常。
<img width="449" alt="image" src="https://github.com/FreedomIntelligence/CMB/assets/15141551/3e8a4c62-712b-4d13-8685-f4f405e52a62">

**Comment by wangxidong06** [comment]
感谢您的提醒，经核实是后台服务器重启之后自动测评服务没有挂起，目前已完成修复，感谢您的反馈！
