### ISSUE TITLE
有没有能跑通的chatglm2-6b的demo？

### ISSUE THREAD

**Issue by chenchch94** [FreedomIntelligence/CMB#7]
尝试跑chatglm和chatglm2的模型，总是有这个bug：  
File "/vepfs/chenchucheng/code/glm/CMB-main/src/../workers/modeling_chatglm_med.py", line 1067, in prepare_inputs_for_generation
    mask_position = seq.index(mask_token)
ValueError: 150001 is not in list

**Comment by g-h-chen** [comment]
> 尝试跑chatglm和chatglm2的模型，总是有这个bug： File "/vepfs/chenchucheng/code/glm/CMB-main/src/../workers/modeling_chatglm_med.py", line 1067, in prepare_inputs_for_generation mask_position = seq.index(mask_token) ValueError: 150001 is not in list

@chenchch94 Hii. 

- [ChatGLM-Med](https://github.com/SCIR-HI/Med-ChatGLM/tree/main#%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD) is not [ChatGLM-2](https://github.com/THUDM/ChatGLM2-6B). The former is SFTed on the basis of [ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B) and the weights can be downloaded [here](https://github.com/SCIR-HI/Med-ChatGLM/tree/main#%E6%A8%A1%E5%9E%8B%E4%B8%8B%E8%BD%BD). 
-  There is a solution for your error [here](https://github.com/SCIR-HI/Med-ChatGLM/tree/main#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98).
