### ISSUE TITLE
关于“CMB被收录于[OpenCompass]中 ”，

### ISSUE THREAD

**Issue by wangzaistone** [FreedomIntelligence/CMB#9]
你好，请问“[2023.09.22] CMB被收录于[OpenCompass]中.” 是指CMB的数据集评测已经可以在OpenCompass代码中直接运行并测试和实现评测了吗？ 还是说只是OpenCompass收录了CMB的数据集而已？

**Comment by wangxidong06** [comment]
您好，只是收录了数据集。
